ALTER TYPE "StudentStudyStatus" ADD VALUE IF NOT EXISTS 'LOW_ACTIVE';
ALTER TYPE "StudentStudyStatus" ADD VALUE IF NOT EXISTS 'SPRINT';
ALTER TYPE "StudentStudyStatus" ADD VALUE IF NOT EXISTS 'INTERVIEW_STAGE';
